# fly.toml app configuration file for iCentral
# Built from Uptime Kuma - Monitoring solution
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "icentral"
primary_region = "mia"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.fly"

[env]
  NODE_ENV = "production"
  UPTIME_KUMA_DB_TYPE = "postgres"
  UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN = "0"
  PORT = "3001"

[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "GET"
    path = "/"
    protocol = "http"

[[mounts]]
  source = "icentral_data"
  destination = "/app/data"
  processes = ["app"]

[deploy]
  release_command = "npm run setup-postgres"
